"""
    THE DROP SITE EXAMPLE SHOWS HOW TO DISTINGUISH THE VARIOUS MIME FORMATS AVAILABLE IN A DRAG
    AND DROP OPERATION.
    IT ACCEPTS DROPS FROM OTHER APPLICATIONS AND DISPLAYS THE MIME FORMATS PROVIDED BY THE DRAG OBJECT.
"""

